<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 ./static/cell.gltf --transform -o Cell.svelte
-->

<script>
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let { fallback, error, children, ref = $bindable(), ...props } = $props()

  const gltf = useGltf('/cell-transformed.glb')
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group rotation={[-Math.PI / 2, 0, 0]}>
      <T.Group
        position={[-0.11, -0.13, -0.05]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <T.Mesh
          geometry={gltf.nodes.Body_1.geometry}
          material={gltf.materials.Mtl}
        />
        <T.Mesh
          geometry={gltf.nodes.Body_2.geometry}
          material={gltf.materials.Mtl}
        />
      </T.Group>
      <T.Mesh
        geometry={gltf.nodes.Body_1_1.geometry}
        material={gltf.materials.Mtl}
        position={[0.07, -0.13, -0.05]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <T.Mesh
        geometry={gltf.nodes.Body_1_2.geometry}
        material={gltf.materials.Mtl2}
        position={[0.03, -0.24, -0.04]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <T.Mesh
        geometry={gltf.nodes.Body_1_3.geometry}
        material={gltf.materials.Mtl2}
        position={[-0.1, -0.13, -0.04]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <T.Mesh
        geometry={gltf.nodes.Body_1_4.geometry}
        material={gltf.materials.texture}
        position={[-0.11, -0.13, 0.05]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <T.Mesh
        geometry={gltf.nodes.Body_1_8.geometry}
        material={gltf.materials.Mtl3}
        position={[0.17, 0.01, 0.06]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
      />
      <T.Mesh
        geometry={gltf.nodes.Body_1_9.geometry}
        material={gltf.materials.Mtl3}
        position={[-0.04, 0.07, 0.06]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <T.Mesh
        geometry={gltf.nodes.Body_1_10.geometry}
        material={gltf.materials.Mtl5}
        position={[-0.01, 0.02, 0.12]}
        rotation={[Math.PI, 0, -Math.PI]}
      />
      <T.Mesh
        geometry={gltf.nodes.Body_1_11.geometry}
        material={gltf.materials.Mtl5}
        position={[0.14, 0.02, 0.12]}
        rotation={[Math.PI, 0, -Math.PI]}
      />
      <T.Mesh
        geometry={gltf.nodes.Body_1_12.geometry}
        material={gltf.materials.Mtl3}
        position={[0.16, -0.03, -0.04]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
      />
      <T.Mesh
        geometry={gltf.nodes.Body_1_13.geometry}
        material={gltf.materials.Mtl3}
        position={[0.1, -0.23, -0.04]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
      />
      <T.Mesh
        geometry={gltf.nodes.Body_1_14.geometry}
        material={gltf.materials.Mtl5}
        position={[0.15, -0.2, 0.02]}
        rotation={[Math.PI, 0, Math.PI / 2]}
      />
      <T.Mesh
        geometry={gltf.nodes.Body_1_15.geometry}
        material={gltf.materials.Mtl5}
        position={[0.15, -0.05, 0.02]}
        rotation={[Math.PI, 0, Math.PI / 2]}
      />
      <T.Mesh
        geometry={gltf.nodes.Body_1_5.geometry}
        material={gltf.materials.texture}
        position={[0.25, 0.12, 0.05]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
      />
      <T.Mesh
        geometry={gltf.nodes.Body_1_6.geometry}
        material={gltf.materials.Mtl7}
        position={[0.21, -0.13, 0.01]}
        rotation={[Math.PI, 0, 0]}
      />
      <T.Mesh
        geometry={gltf.nodes.Body_1_7.geometry}
        material={gltf.materials.texture8}
        position={[0.07, 0.07, 0.09]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
